Repository bakurits/mattermost-plugin-anonymous, pull requests merged in 2020-05, with the labels that each got.

#29 Automatic mock files generator
  Makefile
  mocker.sh
Labels: enhancement

#18 Plugin validation
  go.mod
  go.sum
  server/anonymous/anonymous.go
  server/anonymous/anonymous_test.go
  server/anonymous/mock/anonymous_mock.go
  server/anonymous/verified_plugins.go
  server/command/command_test.go
  server/plugin/mock/plugin_mock.go
  server/plugin/plugin.go
  server/plugin/plugin_api.go
  server/plugin/plugin_api_test.go
Labels: enhancement

#30 Updated README.md
  README.md
Labels: documentation

#27 Added message encryption and decryption
  webapp/package-lock.json
  webapp/package.json
  webapp/src/api_client/api_client.js
  webapp/src/encrypt/encrypt.js
  webapp/src/encrypt/key.js
  webapp/src/encrypt/key_manager.js
  webapp/src/hook/hook.js
  webapp/src/index.js
  webapp/tests/test.js
Labels: enhancement, webapp

#34 Caching
  webapp/src/actions/actions.js
  webapp/src/api_client/api_client.js
  webapp/src/cache/index.js
  webapp/src/cache/lfu_cache.js
  webapp/src/encrypt/key_manager.js
  webapp/src/encrypt/utils.js
  webapp/src/hook/hook.js
  webapp/tests/test.js
Labels: enhancement
